### ISSUE TITLE
根本用不了，微信群没人回消息，账号登录全部429

### ISSUE THREAD

**Issue by IanChen0713** [yuer01/chatgpt_plus_share#3]
别买
根本用不了，微信群没人回消息，账号登录全部429

**Comment by yuer01** [comment]
现在已经不卖了，之前买的还可以用。买的时候有微信联系方式。

**Comment by yuer01** [comment]
如果是付过钱了没有买到账号，发一下订单号，我给您退钱，联系微信 mayixi2013
